### ISSUE TITLE
plugin handling stuff it shouldn't be

### ISSUE THREAD

**Issue by 7-75** [Plixe/WaitBeforeRespawn#1]
I've installed WaitBeforeRespawn (latest relase) but hmm I don't get why do you have to send a message when the command is unkown or change the chat formatting when a player is dead .-.
I can't use the plugin this way but I def would if you could look into those things

**Comment by Plixe** [comment]
Thanks for your report !
I don't really try the plugin with other plugins. You want to say when player type a wrong command, not even a WaitBeforeRespawn's command, the plugin's error message appear ?

Can I have a picture for the chat formatting ? Whitch chat's formatting plugin do you use ? Any lines of the plugin change the chat format, it's strange.
